### ISSUE TITLE
Why only r2r1r0 need to be calculated?

### ISSUE THREAD

**Issue by b1060t** [blat-blatnik/GPU-Life#1]
I am working on a game of life simulation using Unity and I found your project really impressive, especially the optimization part. However, there's one point I can not understand:

You mentioned that only the 3 least significant bits need to be considered. Since the possible value should be 0-9, why we don't have to calculate r3?

**Comment by blat-blatnik** [comment]
Good question - it's because we don't actually care about the exact neighbor count. We only really care if the neighbor count is 3, 4, or anything else (and we don't care exactly what in that case).

Since `3 = 0b011` and `4 = 0b100`, we only need to check the lower 3 bits of the neighbor count.

If the count is 8 or 9, with 3 bits these will just overflow to 0 and 1 respectively - which fall into the the "other" category.

**Comment by b1060t** [comment]
So does it means if I would like to use an arbitrary rule, the optimization will be limited since I have to calculate the exact summation?

**Comment by blat-blatnik** [comment]
Yes, that's right. For a general rule set you will also need to calculate the 4th bit of the neighbor sum (r3).

You'll also need a way to compare the bits to an arbitrary number of values which gets quite messy.

I would actually ditch the bitwise computations entirely for a general rule set and just loop over all 32 bits individually in a for loop. That was the way I did it initially, and it was just as fast since the shader is entirely bound by memory access.

**Comment by b1060t** [comment]
Thank you!
